relativeURLs = true
title = "Niall Peat"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Economics PhD Student, Emory University"
    logo = "NiallHeadshot.jpg" 

[services]
  [services.googleAnalytics]
    ID = 'G-LG3FT0FV6E'
