relativeURLs = true
title = "Maghfira Ramadhani"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, Georgia Institute of Technology"
    logo = "Afi_headshot.jpg" 
    email = "[maghfira.ramadhani@gatech.edu](mailto:maghfira.ramadhani@gatech.edu)"

[services]
  [services.googleAnalytics]
    ID = 'G-LG3FT0FV6E'
